Messenger/Messenger/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', include('registration.urls')),
    path('', include('home.urls')),
    path('settings/', include("settings.urls")),
    path('friends/', include("friends.urls")),
    path('chats/', include("chats.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Messenger/home/urls.py
from django.urls import path
from .views import HomePageView, MyPostsView, DeletePostView, UpdatePostView, UpdateProfileView, render_load_image, render_get_avatar

urlpatterns = [
    path('', view = HomePageView.as_view(), name = 'home'),
    path("my_posts/", view = MyPostsView.as_view(), name = 'my_posts'),
    path("my_posts/<int:pk>/delete/", view = DeletePostView.as_view(), name = 'delete_post'),
    path("my_posts/<int:pk>/change/", view = UpdatePostView.as_view(), name = 'change_post'),
    path("load_image/", view = render_load_image, name = 'load_image'),
    path("get_avatar/", view = render_get_avatar, name = 'get_avatar'),
    path("edit-profile/<int:pk>", view = UpdateProfileView.as_view(), name = 'edit-profile'),
]

Messenger/home/models.py
from django.db import models
from registration.models import Profile

# Create your models here.

class Image(models.Model):
    filename = models.CharField(max_length = 150)
    file = models.ImageField(upload_to = "images/posts")
    uploaded_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.filename

class Tag(models.Model):
    name = models.CharField(max_length=50, unique = True)

    def __str__(self):
        return self.name 

class Post(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    topic = models.CharField(max_length=255)
    content = models.TextField(max_length = 4096)
    tags = models.ManyToManyField(Tag, blank = True)
    images = models.ManyToManyField(Image, blank = True, related_name = 'posts_authored')
    views = models.ManyToManyField(Profile, blank = True, related_name = 'posts_viewed')
    likes = models.ManyToManyField(Profile, blank = True, related_name = 'posts_liked')

    def __str__(self):
        return self.title
    
class Link(models.Model):
    url = models.URLField(max_length = 200)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)

    def __str__(self):
        return f'Посилання для поста "{self.post}"'
    
class Avatar(models.Model):
    image = models.ImageField(upload_to = 'images/avatars')
    profile = models.ForeignKey(Profile, on_delete = models.CASCADE)
    active = models.BooleanField(default = True)
    shown = models.BooleanField(default = True)

    def __str__(self):
        return f'Аватар для профілю "{self.profile}"'

Messenger/home/forms.py
from django import forms
from .models import Post,Tag
from registration.models import User

class UserPostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget = forms.CheckboxSelectMultiple(attrs={
            'class': 'tag-div'
        }),
        label = '',
        required = False,
    )
    
    class Meta:
        model = Post
        fields = ['title', 'tags', 'content']
        widgets = {
            'title': forms.TextInput(attrs = {
                'placeholder': 'Напишіть заголовок публікації'
            }),
            'content': forms.Textarea(attrs = {
                'placeholder': 'Напишіть тему публікації',
            }),
        }
        labels = {
            'title': 'Назва публікації',
            'content': '',
        }
        

class ChangeUserPostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget = forms.CheckboxSelectMultiple(attrs={
            'class': 'tag-div'
        }),
        label = '',
        required = False,
    )
    class Meta:
        model = Post
        fields = ['title', 'tags', 'content']
        widgets = {
            'title': forms.TextInput(attrs = {
                'placeholder': 'Змініть заголовок публікації'
            }),
            'content': forms.Textarea(attrs = {
                'placeholder': 'Змініть тему публікації',
            }),
        }
        labels = {
            'title': 'Назва публікації',
            'content': '',
            'tags': ''
        }

class FirstEditInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username"]
        labels = {
            "first_name": "Ім'я",
            "last_name": "Прізвище",
            "username": "Ім'я користувача",
        }
        widgets = {
            "first_name": forms.TextInput(attrs = {
                "placeholder": "Введіть Ваше ім’я"
            }),
            "last_name": forms.TextInput(attrs = {
                "placeholder": "Введіть Ваше прізвище"
            }),
            "username": forms.TextInput(attrs = {
                "value": "@"
            }),
        }
        help_texts = {
               'username': None
           }

Messenger/home/views.py
import os, shutil

from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import FormMixin
from django.views.generic import DeleteView, UpdateView
from .forms import UserPostForm, ChangeUserPostForm, FirstEditInfoForm
from .models import Post, Image, Link, Avatar
from friends.models import Friendship
from registration.models import User, Profile
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpRequest, JsonResponse, HttpResponse
from django.core.files.base import ContentFile
from PIL import Image as PILimage
from io import BytesIO
from django.db.models import Q


class HomePageView(LoginRequiredMixin, FormMixin, ListView):
    model = Post
    form_class = UserPostForm
    template_name = "home/home.html"
    context_object_name = "posts" 
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if not self.request.user.username:
            context["edit_form"] = FirstEditInfoForm()
        else:
            context["my_posts_length"] = Post.objects.filter(author=self.request.user.id).count()
            friendship_list = Friendship.objects.filter(Q(profile1_id=self.request.user.id) | Q(profile2_id=self.request.user.id), accepted=True)[:3]
            for friend in friendship_list:
                if friend.profile1_id == self.request.user.id:
                    try:
                        context["my_friends"] = context["my_friends"], User.objects.get(id = Profile.objects.get(id = friend.profile2_id).user_id)
                    except:
                        context["my_friends"] = [User.objects.get(id = Profile.objects.get(id = friend.profile2_id).user_id)]
                else:
                    try:
                        context["my_friends"] = context["my_friends"], User.objects.get(id = Profile.objects.get(id = friend.profile1_id).user_id)
                    except:
                        context["my_friends"] = [User.objects.get(id = Profile.objects.get(id = friend.profile1_id).user_id)]

        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self, form):
        post = form.save(commit=False)
        user = User.objects.get(id = self.request.user.id)
        try:
            post.author = Profile.objects.create(user=user)
        except:
            post.author = Profile.objects.get(user=user)
        try:
            dir_path = os.path.abspath(os.path.join(__file__, "..", "static", "images", "temp_post_images", self.request.user.email))
            images = []
            for filename in os.listdir(dir_path):
                print("filename (home) =", filename)
                file_path = os.path.join(dir_path, filename)

                # Open image with PIL
                pil_image = PILimage.open(file_path)

                # Save it to BytesIO
                image_io = BytesIO()
                pil_image.save(image_io, format=pil_image.format)
                image_content = ContentFile(image_io.getvalue(), name=filename)
                # Create and save the Image model
                image = Image.objects.create(
                    filename=filename,
                    file=image_content
                )
                images.append(image)
            shutil.rmtree(dir_path)
        except:
            pass

        post.save()
        form.save_m2m()
        post.images.set(images) 

        link = self.request.POST.get('link')
        Link.objects.create(
            url = link,
            post = post
        )

        return redirect("/")

class MyPostsView(LoginRequiredMixin, FormMixin, ListView):
    queryset = Post
    form_class = ChangeUserPostForm
    template_name = "my_posts/my_posts.html"
    context_object_name = "posts" 
    success_url = "/"

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if not self.request.user.username:
            context["edit_form"] = FirstEditInfoForm()
        else:
            context["my_posts_length"] = Post.objects.filter(author=self.request.user.id).count()
            friendship_list = Friendship.objects.filter(Q(profile1_id=self.request.user.id) | Q(profile2_id=self.request.user.id), accepted=True)[:3]
            for friend in friendship_list:
                if friend.profile1_id == self.request.user.id:
                    try:
                        context["my_friends"] = context["my_friends"], User.objects.get(id = Profile.objects.get(id = friend.profile2_id).user_id)
                    except:
                        context["my_friends"] = [User.objects.get(id = Profile.objects.get(id = friend.profile2_id).user_id)]
                else:
                    try:
                        context["my_friends"] = context["my_friends"], User.objects.get(id = Profile.objects.get(id = friend.profile1_id).user_id)
                    except:
                        context["my_friends"] = [User.objects.get(id = Profile.objects.get(id = friend.profile1_id).user_id)]

        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        
    def form_valid(self, form):
        post = form.save(commit=False)
        user = User.objects.get(id = self.request.user.id)
        try:
            post.author = Profile.objects.create(user=user)
        except:
            post.author = Profile.objects.get(user=user)
        try:
            dir_path = os.path.abspath(os.path.join(__file__, "..", "static", "images", "temp_post_images", self.request.user.email))
            images = []
            for filename in os.listdir(dir_path):
                print("filename (home) =", filename)
                file_path = os.path.join(dir_path, filename)

                # Open image with PIL
                pil_image = PILimage.open(file_path)

                # Save it to BytesIO
                image_io = BytesIO()
                pil_image.save(image_io, format=pil_image.format)
                image_content = ContentFile(image_io.getvalue(), name=filename)
                # Create and save the Image model
                image = Image.objects.create(
                    filename=filename,
                    file=image_content
                )
                images.append(image)
            shutil.rmtree(dir_path)
        except:
            pass

        link = self.request.POST.get('link')
        Link.objects.create(
            ulr = link,
            post = post.id
        )

        post.save()
        form.save_m2m()
        post.images.set(images) 
        return redirect("/my_posts")

class DeletePostView(DeleteView):
    model = Post
    success_url = reverse_lazy("my_posts")

class UpdatePostView(UpdateView):
    model = Post
    fields = ['title', 'content']
    success_url = reverse_lazy("my_posts")

class UpdateProfileView(UpdateView):
    model = User
    fields = ["first_name", "last_name", "username"]
    success_url = reverse_lazy("home")

    def post(self, request, *args, **kwargs):
        profile = Profile.objects.create(
            user = request.user
        )
        profile.save()
        return super().post(request, *args, **kwargs)

def render_load_image(request: HttpRequest):
    image = request.FILES.get("image")
    print("image =", image)
    dir_path = os.path.abspath(os.path.join(__file__, "..", "static", "images", "temp_post_images", request.user.email))
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)
    file_path = os.path.abspath(os.path.join(dir_path, image.name))
    with open(file_path, 'wb+') as destination:
        for chunk in image.chunks():
            destination.write(chunk)
        
    imageEl = PILimage.open(image)

    width, height = imageEl.size
    
    return JsonResponse({"width": width, "height": height, "email": request.user.email})

def render_get_avatar(request):
    response = HttpResponse("Cookie has been set!")
    profile = Profile.objects.get(user_id = User.objects.get(id = request.user.id).id)
    avatar_path = Avatar.objects.get(profile_id = profile.id).image
    response.set_cookie('my_avatar', avatar_path)
    return response

Messenger/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% load post_forms %}

{% block title %}
    Домашня сторінка
{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/home/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/home/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/home/info-form.css' %}">
{% endblock %}

{% block content %}

    <div class="dark-background">{% form_for_post "" %}</div>

    <div class="my-info">
        <div class="about-me">
            <div class="me">
                <div class="my-avatar"><div class="I-am-online"></div></div>
                
                <span class="username">
                    <p class="name">{{ request.user.first_name }} {{ request.user.last_name }}</p>
                    <p class="username"> {{ request.user.username }} </p>
                </span>
            </div>
            <div class="my-status">
                <span>
                    <p class="status-number">{{ my_posts_length }}</p>
                    <p class="status-title">Дописи</p>
                </span>
                <div class="vtc-line"></div>
                <span>
                    <p class="status-number">0</p>
                    <p class="status-title">Читачі</p>
                </span>
                <div class="vtc-line"></div>
                <span>
                    <p class="status-number">{{ my_friends | length }}</p>
                    <p class="status-title">Друзі</p>
                </span>
            </div>
        </div>

        <div class="friends">
            <span class="top-text">
                <p class="section-title">
                    <img src="{% static 'images/friends-grey.png' %}" alt="" class="small-images"> Запити
                </p>
                <p class="see-all">Дивитись всі</p>
            </span>
            <div class="friend-requests">
                {% for friend in my_friends %}
                    <div class="request">
                        <div class="avatar-container"></div>
                        <span class="friend-info">
                            <p class="friend-name">{{ friend.first_name }} {{ friend.last_name }}</p>
                            <p class="friend-request-followers">4.3к підписників</p>
                        </span>
                    </div>
                {% endfor %}
                <!-- <div class="request">
                    <div class="avatar-container"></div>
                    <img class="avatar" src="{% static 'images/friend2.jpg' %}" alt="" class="small-images">
                    <span class="friend-info">
                        <p class="friend-name">Ann Ann</p>
                        <p class="friend-request-followers">1.6к підписників</p>
                    </span>
                </div>
                <div class="request">
                    <div class="avatar-container"></div>
                    <img class="avatar" src="{% static 'images/friend3.jpg' %}" alt=""class="small-images"> 
                    <span class="friend-info">
                        <p class="friend-name">Yeugen Jenua</p>
                        <p class="friend-request-followers">10.3к підписників</p>
                    </span>
                </div> -->
            </div>
        </div>

        <div class="chats">
            <span class="top-text">
                <p class="section-title">
                    <img src="{% static 'images/chats-grey.png' %}" alt="" class="small-images"> Повідомлення
                </p>
                <p class="see-all">Дивитись всі</p>
            </span>
            <div class="messages">
                <div class="request">
                    <div class="avatar-container"></div>
                    <!-- <img class="avatar" src="{% static 'images/friend4.jpg' %}" alt="" class="small-images"> -->
                    <span class="friend-info">
                        <p class="friend-name">Mona Lisa</p>
                        <p class="friend-message">Привіт! Як справи ?</p>
                    </span>
                </div>
                <div class="request">
                    <div class="avatar-container"></div>
                    <!-- <img class="avatar" src="{% static 'images/friend5.jpg' %}" alt="" class="small-images"> -->
                    <span class="friend-info">
                        <p class="friend-name">Ann Ti</p>
                        <p class="friend-message">Привіт!</p>
                    </span>
                </div>
                <div class="request">
                    <div class="avatar-container"></div>
                    <!-- <img class="avatar" src="{% static 'images/friend6.jpg' %}" alt="" class="small-images"> -->
                    <span class="friend-info">
                        <p class="friend-name">Ness Ty</p>
                        <p class="friend-message">Привіт!</p>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div class="social-media-feed">
        <div class="create-publication">
            <span class="thoughts">
                <p class="what">Про що ти зараз думаєш?</p>
            </span>
            <div class="custom">
                <div class="add-image">
                    <img src="{% static 'images/add-image.png' %}" alt="" class="small-images">
                </div>
                <div class="add-emoji">
                    <img src="{% static 'images/add-emoji.png' %}" alt="" class="small-images">
                </div>
                <div id="createPublication" class="publish">
                    <p>Перейти до оформлення</p>
                </div>
            </div>
        </div>

        
        <div class="feed">

            {% if edit_form %}
                <form class="edit-info-form" action="{% url 'edit-profile' request.user.id %}" method="post">
                    {% csrf_token %}
                    <h2>Додай деталі про себе</h2>
                    {{ edit_form }}
                    <span>
                        <button class="post-p">Продовжити</button>
                    </span>
                </form>
            {% endif %}
        
            {% for post in object_list %}
                <div class="post">
                    <div class="creator">
                        <div class="creator-info">
                            <div class="main-info">
                                <div class="avatar-container">
                                    <!-- <img class="avatar" src="{% static 'images/avatar2.jpg' %}" alt="" class="small-images"> -->
                                    <div class="is-offline"></div>
                                </div>
                                <p class="creator-name">{{ post.author }}</p>
                            </div>
                        </div>
                        <img src="{% static 'images/dots.png' %}" alt="" class="dots small-images">
                    </div>
                    <div class="post-content">
                        <div class="post-text">
                            <p class="title">{{ post.title }}</p>
                            <p>
                                {{ post.content }}
                            </p>
                            <p class="post-tags">
                                {% for tag in post.tags.all %}
                                    {{ tag.name }}
                                {% endfor %}
                            </p>
                            <p>
                                {% for link in post.link_set.all %}
                                    <a href="{{ link.url }}">{{ link.url }}</a>
                                {% endfor %}
                            <div class="post_images_container">
                                {% for image in post.images.all %}
                                    <img class="post_image" src="{{ image.file.url }}" alt="{{ image.filename }}">
                                {% endfor %}
                            </div>
                            
                        </div>
                        <div class="aktives">
                            <div class="likes">
                                <img src="{% static 'images/likes.png' %}" alt="" class="small-images">
                                <p>{{ post.likes }} Вподобань</p>
                            </div>
                            <div class="views">
                                <img src="{% static 'images/views.png' %}" alt="" class="small-images">
                                <p>{{ post.views }} Переглядів</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        const staticBase = "{% static 'images/temp_post_images/' %}";
    </script>
    <script src="{% static 'js/showForm.js' %}"></script>
    <script src="{% static 'js/addImage.js' %}"></script>
    <script src="{% static 'js/tags.js' %}"></script>
{% endblock %}